### ISSUE TITLE
Adding unit price

### ISSUE THREAD

**Issue by XiSmartElf** [Matrix-Guy/binance-valuations#1]
Great work! Can you also add the unit price as well (int multiple currencies)? I see so far only shows the asset total for each coin, a unit price of each would be awesome!

**Comment by xangelix** [comment]
Thanks for the feature request @XiSmartElf ! I have added this to the upcoming features list located in README.md, it will likely be added sometime this week. (1/15/2018 - 1/22/2018) This issue will be closed when the feature is added.

**Comment by xangelix** [comment]
Feature added in: 
Release: [v0.3.2](https://github.com/Matrix-Guy/binance-valuations/releases/tag/v0.3.2)
Commit: 67db9810057cd89d0ce35e1c83c5f1a42deec931

**Comment by XiSmartElf** [comment]
Awesome. see that working now! Thanks!
